/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TButton {
        "disabled"?: boolean;
        "href"?: string;
        "innerTabindex"?: number;
        "name"?: string;
        "setFocus": () => Promise<void>;
        "size"?: 'small' | 'large';
        "target"?: string;
        "type"?: 'reset' | 'submit' | 'button';
        "value"?: string;
        "variant"?: string;
    }
    interface TChip {
        "closeable": boolean;
        "text": string;
    }
    interface TChipSelect {
    }
    interface TColorEditor {
        "color": string;
        "colorname": string;
    }
    interface TContainer {
    }
    interface TDisplay {
    }
    interface TInput {
        "fullwidth": boolean;
        "placeholder": string;
        "type": string;
        "value": any;
    }
    interface TMenu {
    }
    interface TMenuItem {
        "header": boolean;
        "href": string;
    }
    interface TModal {
        "isOpen": boolean;
    }
    interface TSidebar {
        "header"?: string;
    }
    interface TThemeEditor {
        "isOpen": boolean;
        "theme": any;
    }
    interface TThemeManager {
        "open": () => Promise<void>;
        "resetTheme": () => Promise<void>;
    }
    interface TToast {
        "fadeDuration"?: number;
        "open": () => Promise<void>;
        "opened"?: boolean;
        "positionRight"?: number;
        "positionTop"?: number;
        "size"?: string;
        "variant"?: string;
    }
}
declare global {
    interface HTMLTButtonElement extends Components.TButton, HTMLStencilElement {
    }
    var HTMLTButtonElement: {
        prototype: HTMLTButtonElement;
        new (): HTMLTButtonElement;
    };
    interface HTMLTChipElement extends Components.TChip, HTMLStencilElement {
    }
    var HTMLTChipElement: {
        prototype: HTMLTChipElement;
        new (): HTMLTChipElement;
    };
    interface HTMLTChipSelectElement extends Components.TChipSelect, HTMLStencilElement {
    }
    var HTMLTChipSelectElement: {
        prototype: HTMLTChipSelectElement;
        new (): HTMLTChipSelectElement;
    };
    interface HTMLTColorEditorElement extends Components.TColorEditor, HTMLStencilElement {
    }
    var HTMLTColorEditorElement: {
        prototype: HTMLTColorEditorElement;
        new (): HTMLTColorEditorElement;
    };
    interface HTMLTContainerElement extends Components.TContainer, HTMLStencilElement {
    }
    var HTMLTContainerElement: {
        prototype: HTMLTContainerElement;
        new (): HTMLTContainerElement;
    };
    interface HTMLTDisplayElement extends Components.TDisplay, HTMLStencilElement {
    }
    var HTMLTDisplayElement: {
        prototype: HTMLTDisplayElement;
        new (): HTMLTDisplayElement;
    };
    interface HTMLTInputElement extends Components.TInput, HTMLStencilElement {
    }
    var HTMLTInputElement: {
        prototype: HTMLTInputElement;
        new (): HTMLTInputElement;
    };
    interface HTMLTMenuElement extends Components.TMenu, HTMLStencilElement {
    }
    var HTMLTMenuElement: {
        prototype: HTMLTMenuElement;
        new (): HTMLTMenuElement;
    };
    interface HTMLTMenuItemElement extends Components.TMenuItem, HTMLStencilElement {
    }
    var HTMLTMenuItemElement: {
        prototype: HTMLTMenuItemElement;
        new (): HTMLTMenuItemElement;
    };
    interface HTMLTModalElement extends Components.TModal, HTMLStencilElement {
    }
    var HTMLTModalElement: {
        prototype: HTMLTModalElement;
        new (): HTMLTModalElement;
    };
    interface HTMLTSidebarElement extends Components.TSidebar, HTMLStencilElement {
    }
    var HTMLTSidebarElement: {
        prototype: HTMLTSidebarElement;
        new (): HTMLTSidebarElement;
    };
    interface HTMLTThemeEditorElement extends Components.TThemeEditor, HTMLStencilElement {
    }
    var HTMLTThemeEditorElement: {
        prototype: HTMLTThemeEditorElement;
        new (): HTMLTThemeEditorElement;
    };
    interface HTMLTThemeManagerElement extends Components.TThemeManager, HTMLStencilElement {
    }
    var HTMLTThemeManagerElement: {
        prototype: HTMLTThemeManagerElement;
        new (): HTMLTThemeManagerElement;
    };
    interface HTMLTToastElement extends Components.TToast, HTMLStencilElement {
    }
    var HTMLTToastElement: {
        prototype: HTMLTToastElement;
        new (): HTMLTToastElement;
    };
    interface HTMLElementTagNameMap {
        "t-button": HTMLTButtonElement;
        "t-chip": HTMLTChipElement;
        "t-chip-select": HTMLTChipSelectElement;
        "t-color-editor": HTMLTColorEditorElement;
        "t-container": HTMLTContainerElement;
        "t-display": HTMLTDisplayElement;
        "t-input": HTMLTInputElement;
        "t-menu": HTMLTMenuElement;
        "t-menu-item": HTMLTMenuItemElement;
        "t-modal": HTMLTModalElement;
        "t-sidebar": HTMLTSidebarElement;
        "t-theme-editor": HTMLTThemeEditorElement;
        "t-theme-manager": HTMLTThemeManagerElement;
        "t-toast": HTMLTToastElement;
    }
}
declare namespace LocalJSX {
    interface TButton {
        "disabled"?: boolean;
        "href"?: string;
        "innerTabindex"?: number;
        "name"?: string;
        "size"?: 'small' | 'large';
        "target"?: string;
        "type"?: 'reset' | 'submit' | 'button';
        "value"?: string;
        "variant"?: string;
    }
    interface TChip {
        "closeable"?: boolean;
        "onChip-close"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface TChipSelect {
    }
    interface TColorEditor {
        "color"?: string;
        "colorname"?: string;
        "onColorChanged"?: (event: CustomEvent<any>) => void;
    }
    interface TContainer {
    }
    interface TDisplay {
    }
    interface TInput {
        "fullwidth"?: boolean;
        "onValueChanged"?: (event: CustomEvent<string>) => void;
        "placeholder"?: string;
        "type"?: string;
        "value"?: any;
    }
    interface TMenu {
    }
    interface TMenuItem {
        "header"?: boolean;
        "href"?: string;
        "onMenu-item-clicked"?: (event: CustomEvent<void>) => void;
    }
    interface TModal {
        "isOpen"?: boolean;
        "onModalClosed"?: (event: CustomEvent<boolean>) => void;
    }
    interface TSidebar {
        "header"?: string;
    }
    interface TThemeEditor {
        "isOpen"?: boolean;
        "onThemeEdited"?: (event: CustomEvent<any>) => void;
        "theme"?: any;
    }
    interface TThemeManager {
    }
    interface TToast {
        "fadeDuration"?: number;
        "onToast-closed"?: (event: CustomEvent<void>) => void;
        "opened"?: boolean;
        "positionRight"?: number;
        "positionTop"?: number;
        "size"?: string;
        "variant"?: string;
    }
    interface IntrinsicElements {
        "t-button": TButton;
        "t-chip": TChip;
        "t-chip-select": TChipSelect;
        "t-color-editor": TColorEditor;
        "t-container": TContainer;
        "t-display": TDisplay;
        "t-input": TInput;
        "t-menu": TMenu;
        "t-menu-item": TMenuItem;
        "t-modal": TModal;
        "t-sidebar": TSidebar;
        "t-theme-editor": TThemeEditor;
        "t-theme-manager": TThemeManager;
        "t-toast": TToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "t-button": LocalJSX.TButton & JSXBase.HTMLAttributes<HTMLTButtonElement>;
            "t-chip": LocalJSX.TChip & JSXBase.HTMLAttributes<HTMLTChipElement>;
            "t-chip-select": LocalJSX.TChipSelect & JSXBase.HTMLAttributes<HTMLTChipSelectElement>;
            "t-color-editor": LocalJSX.TColorEditor & JSXBase.HTMLAttributes<HTMLTColorEditorElement>;
            "t-container": LocalJSX.TContainer & JSXBase.HTMLAttributes<HTMLTContainerElement>;
            "t-display": LocalJSX.TDisplay & JSXBase.HTMLAttributes<HTMLTDisplayElement>;
            "t-input": LocalJSX.TInput & JSXBase.HTMLAttributes<HTMLTInputElement>;
            "t-menu": LocalJSX.TMenu & JSXBase.HTMLAttributes<HTMLTMenuElement>;
            "t-menu-item": LocalJSX.TMenuItem & JSXBase.HTMLAttributes<HTMLTMenuItemElement>;
            "t-modal": LocalJSX.TModal & JSXBase.HTMLAttributes<HTMLTModalElement>;
            "t-sidebar": LocalJSX.TSidebar & JSXBase.HTMLAttributes<HTMLTSidebarElement>;
            "t-theme-editor": LocalJSX.TThemeEditor & JSXBase.HTMLAttributes<HTMLTThemeEditorElement>;
            "t-theme-manager": LocalJSX.TThemeManager & JSXBase.HTMLAttributes<HTMLTThemeManagerElement>;
            "t-toast": LocalJSX.TToast & JSXBase.HTMLAttributes<HTMLTToastElement>;
        }
    }
}
