/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TColorEditor {
        "color": string;
        "colorname": string;
    }
    interface TContainer {
    }
    interface TDisplay {
    }
    interface TInput {
        "placeholder": string;
        "type": string;
        "value": any;
    }
    interface TMenu {
    }
    interface TMenuItem {
        "header": boolean;
        "href": string;
    }
    interface TModal {
        "isOpen": boolean;
    }
    interface TSidebar {
    }
    interface TThemeEditor {
        "isOpen": boolean;
    }
    interface TThemeManager {
    }
}
declare global {
    interface HTMLTColorEditorElement extends Components.TColorEditor, HTMLStencilElement {
    }
    var HTMLTColorEditorElement: {
        prototype: HTMLTColorEditorElement;
        new (): HTMLTColorEditorElement;
    };
    interface HTMLTContainerElement extends Components.TContainer, HTMLStencilElement {
    }
    var HTMLTContainerElement: {
        prototype: HTMLTContainerElement;
        new (): HTMLTContainerElement;
    };
    interface HTMLTDisplayElement extends Components.TDisplay, HTMLStencilElement {
    }
    var HTMLTDisplayElement: {
        prototype: HTMLTDisplayElement;
        new (): HTMLTDisplayElement;
    };
    interface HTMLTInputElement extends Components.TInput, HTMLStencilElement {
    }
    var HTMLTInputElement: {
        prototype: HTMLTInputElement;
        new (): HTMLTInputElement;
    };
    interface HTMLTMenuElement extends Components.TMenu, HTMLStencilElement {
    }
    var HTMLTMenuElement: {
        prototype: HTMLTMenuElement;
        new (): HTMLTMenuElement;
    };
    interface HTMLTMenuItemElement extends Components.TMenuItem, HTMLStencilElement {
    }
    var HTMLTMenuItemElement: {
        prototype: HTMLTMenuItemElement;
        new (): HTMLTMenuItemElement;
    };
    interface HTMLTModalElement extends Components.TModal, HTMLStencilElement {
    }
    var HTMLTModalElement: {
        prototype: HTMLTModalElement;
        new (): HTMLTModalElement;
    };
    interface HTMLTSidebarElement extends Components.TSidebar, HTMLStencilElement {
    }
    var HTMLTSidebarElement: {
        prototype: HTMLTSidebarElement;
        new (): HTMLTSidebarElement;
    };
    interface HTMLTThemeEditorElement extends Components.TThemeEditor, HTMLStencilElement {
    }
    var HTMLTThemeEditorElement: {
        prototype: HTMLTThemeEditorElement;
        new (): HTMLTThemeEditorElement;
    };
    interface HTMLTThemeManagerElement extends Components.TThemeManager, HTMLStencilElement {
    }
    var HTMLTThemeManagerElement: {
        prototype: HTMLTThemeManagerElement;
        new (): HTMLTThemeManagerElement;
    };
    interface HTMLElementTagNameMap {
        "t-color-editor": HTMLTColorEditorElement;
        "t-container": HTMLTContainerElement;
        "t-display": HTMLTDisplayElement;
        "t-input": HTMLTInputElement;
        "t-menu": HTMLTMenuElement;
        "t-menu-item": HTMLTMenuItemElement;
        "t-modal": HTMLTModalElement;
        "t-sidebar": HTMLTSidebarElement;
        "t-theme-editor": HTMLTThemeEditorElement;
        "t-theme-manager": HTMLTThemeManagerElement;
    }
}
declare namespace LocalJSX {
    interface TColorEditor {
        "color"?: string;
        "colorname"?: string;
        "onColorChanged"?: (event: CustomEvent<any>) => void;
    }
    interface TContainer {
    }
    interface TDisplay {
    }
    interface TInput {
        "onValueChanged"?: (event: CustomEvent<string>) => void;
        "placeholder"?: string;
        "type"?: string;
        "value"?: any;
    }
    interface TMenu {
    }
    interface TMenuItem {
        "header"?: boolean;
        "href"?: string;
    }
    interface TModal {
        "isOpen"?: boolean;
        "onModalClosed"?: (event: CustomEvent<boolean>) => void;
    }
    interface TSidebar {
    }
    interface TThemeEditor {
        "isOpen"?: boolean;
    }
    interface TThemeManager {
    }
    interface IntrinsicElements {
        "t-color-editor": TColorEditor;
        "t-container": TContainer;
        "t-display": TDisplay;
        "t-input": TInput;
        "t-menu": TMenu;
        "t-menu-item": TMenuItem;
        "t-modal": TModal;
        "t-sidebar": TSidebar;
        "t-theme-editor": TThemeEditor;
        "t-theme-manager": TThemeManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "t-color-editor": LocalJSX.TColorEditor & JSXBase.HTMLAttributes<HTMLTColorEditorElement>;
            "t-container": LocalJSX.TContainer & JSXBase.HTMLAttributes<HTMLTContainerElement>;
            "t-display": LocalJSX.TDisplay & JSXBase.HTMLAttributes<HTMLTDisplayElement>;
            "t-input": LocalJSX.TInput & JSXBase.HTMLAttributes<HTMLTInputElement>;
            "t-menu": LocalJSX.TMenu & JSXBase.HTMLAttributes<HTMLTMenuElement>;
            "t-menu-item": LocalJSX.TMenuItem & JSXBase.HTMLAttributes<HTMLTMenuItemElement>;
            "t-modal": LocalJSX.TModal & JSXBase.HTMLAttributes<HTMLTModalElement>;
            "t-sidebar": LocalJSX.TSidebar & JSXBase.HTMLAttributes<HTMLTSidebarElement>;
            "t-theme-editor": LocalJSX.TThemeEditor & JSXBase.HTMLAttributes<HTMLTThemeEditorElement>;
            "t-theme-manager": LocalJSX.TThemeManager & JSXBase.HTMLAttributes<HTMLTThemeManagerElement>;
        }
    }
}
